version: "3.3"
services:
  app :
    build: ./flow/
  db:
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    
    build: ./database/
    ports:
      - "5432:5432"
    restart: always
  
  api_service:
    build: ./app/
    ports:
      - "8080:8080"
    restart: always
   